package Level_1;

/**
 * Operation High Vantage - Level 1
 * Target Time: 15 Minutes
 */
public class Main {

    /**
     * Takes an array of altitude integers.
     * Returns a new array with all negative numbers removed.
     */
    public static int[] cleanData(int[] arr) {
        // Write your logic here
        
        return new int[0]; 
    }

    /**
     * Takes an array of cleaned altitude integers.
     * Returns the highest altitude.
     */
    public static int findPeak(int[] arr) {
        // Write your logic here
        
        return 0;
    }
}
